version: '3.7'

services:
  nginx:
    container_name: con_laravel_sample
    # lokasi source code
    build:
      context: ./
      dockerfile: web.dockerfile
    # path untuk source di dalam docker
    volumes:
      - ./:/var/www
    image: nginx:latest
    ports:
      - "8070:80"

  app:
    container_name: app_laravel_sample
    build:
      context: ./
      dockerfile: app.dockerfile
    image: app_laravel_docker
    volumes:
      - ./:/var/www

